### ISSUE TITLE
Use AND instead of OR when selecting tags

### ISSUE THREAD

**Issue by GeertvanGeest** [sib-swiss/glittr#14]
Currently, when selecting two tags (e.g. 'single-cell sequencing' and 'R') you get all courses with the tag 'single-cell sequencing' *or* with the tag 'R'. I think there are more use cases for people looking for courses with both tags, so 'single-cell sequencing' *and* 'R'. Therefore, it is probably better to change it to 'and'.

**Comment by yhaefligsib** [comment]
Added the possibility to let user decide and make the default the "AND" operator.
![image](https://github.com/sib-swiss/glittr/assets/118164920/f68b4d76-ec41-4e2e-9382-b38155be9625)
When in "AND" operator I removed the option to select all tags of a category as this make no sense, it will always display empty results as no repositories have all tags of a category.

**Comment by GeertvanGeest** [comment]
Very cool, it works really nice like this.

**Comment by yhaefligsib** [comment]
Merged live #21
