### ISSUE TITLE
Add terms of use

### ISSUE THREAD

**Issue by GeertvanGeest** [sib-swiss/glittr#27]
Add terms of use to:
- footer of the main page (example https://www.expasy.org/)
- close to the submit button at https://glittr.org/contribute the sentence 'By submitting a repository, you hereby acknowledge and confirm that you have read the Glittr Terms of Use and that you agree to comply with them' (hyperlink 'Glittr Terms of Use')

Terms of use:

[20240207_Terms of Use for Glittr_final.docx](https://github.com/sib-swiss/glittr/files/14615874/20240207_Terms.of.Use.for.Glittr_final.docx)

**Comment by yhaefligsib** [comment]
added in merge #28
