### ISSUE TITLE
Tag order during API calls

### ISSUE THREAD

**Issue by GeertvanGeest** [sib-swiss/glittr#36]
When I do an API call for a specific repository, e.g. https://glittr.org/api/repositories?filter[name]=theislab/single-cell-tutorial, the tag order is the same as represented on the website. In the example the first (and main tag) would be 'Single-cell sequencing'. However, when I do an API call on all repositories with https://glittr.org/api/repositories. The order of the tags is different (the example is entry 42): 

<img width="630" alt="Screenshot 2024-10-18 at 09 59 34" src="https://github.com/user-attachments/assets/c870345d-3468-496f-a253-4708bbdb3df5">

Here, the main tag is 'Python'. I would expect to see the same tag order here as on the website.

**Comment by GeertvanGeest** [comment]
The tag order is also correct with pages:

https://glittr.org/api/repositories?page[size]=50&page[number]=1

<img width="818" alt="Screenshot 2024-10-18 at 10 23 11" src="https://github.com/user-attachments/assets/850be42f-9aec-467f-9a52-5acac1c981e5">

**Comment by yhaefligsib** [comment]
the order of tags has been fixed in API calls
![image](https://github.com/user-attachments/assets/0aa87c3d-9c7b-41b7-8604-538c6f145229)

**Comment by GeertvanGeest** [comment]
Thanks a lot @yhaefligsib !

**Comment by GeertvanGeest** [comment]
The issue seems to be back, is that possible? 

<img width="544" alt="Screenshot 2024-11-15 at 15 46 11" src="https://github.com/user-attachments/assets/36997243-e7c1-43d9-bf57-da1e8d48444d">

**Comment by yhaefligsib** [comment]
Hi,

I saw that the order column in the model relation was missing, so I think the value of the order column was not always loaded, preventing the correct sorting of the tags.

I pushed a new fix that should solve the issue for good.
I also fixed the order displayed in the admin which was wrong, let me know if you see it happen somewhere!
