### ISSUE TITLE
User feedback after adding a resource

### ISSUE THREAD

**Issue by GeertvanGeest** [sib-swiss/glittr#8]
It would be nice to give the user feedback by e-mail after a course submission has been accepted/declined. This would increase user involvement.

**Comment by GeertvanGeest** [comment]
The e-mail after acceptance:

```
Dear [name],

Thank you for adding your material to Glittr.org! These contributions are very much appreciated by the community. 

Here's what the curator wrote:

[Comments]

Best wishes,
Geert from Glittr.org
```

After a decline:

```
Dear [name],

Thanks for submitting to Glittr.org. Unfortunately, your submission did not pass our checks.

Here's what the curator wrote:

[Comments]

Best wishes,
the Glittr team
```

So signed with a name after acceptance (a bit more personal), and without after decline (to not make it personal ;)). 
It would require to write something in the comments box after each submission, but I think that makes sense any way.

**Comment by yhaefligsib** [comment]
I just added the url of the submission instead of "your material" so it's easier for recipient and you who also receive the mail in bcc to keep track of which resource it was  

![image](https://github.com/sib-swiss/glittr/assets/118164920/3d8e6997-1d8d-4dbb-bf1b-ed9b7a77ac25)
